---
title: "AdvancedR3 Quarto document"
author: "Simranjeet Kaur"
format: html
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, `Mean (SD)` = MeanSD) |>
  knitr::kable(caption = "Descriptive Statistics of the Metabolites")
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

#remove chunk

```{r}
log_reg_specs <- logistic_reg() |>
  set_engine("glm")

log_reg_specs
```

#Keep

```{r}
lipidomics_wide <- lipidomics |>
  column_values_to_snake_case(metabolite) |>
  metabolites_to_wider()
lipidomics_wide
```

#remove chunk

```{r}
recipe_specs <- lipidomics_wide |>
  create_recipe_spec(metabolite_cholesterol)
recipe_specs
```

#remove chunk

```{r}
workflow() |>
  add_model(log_reg_specs) |>
  add_recipe(recipe_specs)
```

## Running multiple models

```{r}
model_estimates <- tar_read(df_model_estimates)
```

## Visualizing the model estimates

```{r}
tar_read(fig_model_estimates)
```
